#!/stage1/busybox sh
echo "OHAI, stage1 init starting" > /dev/kmsg
export _PATH="$PATH"
export PATH=/stage1

force_recovery="0"

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

while ! busybox test -d /sys/devices/platform/s3c-sdhci.0/mmc_host/mmc0/mmc0:0001 ; do
	echo "Waiting for internal mmc..."
	busybox sleep 1
done

/lvm/sbin/lvm vgscan --mknodes --ignorelockingfailure
/lvm/sbin/lvm vgchange -aly --ignorelockingfailure

busybox mount -t ext4 /dev/lvpool/system /system
busybox mount -t yaffs2 /dev/block/mtdblock2 /cache

image=/stage1/ramdisk.cpio

if busybox test -e /cache/.startrecovery || busybox grep -q bootmode=2 /proc/cmdline || busybox grep -q recovery /proc/cmdline ; then
	# recovery boot
	busybox rm -fr /cache/.startrecovery
	image=/stage1/ramdisk-recovery.cpio

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
elif ! busybox test -e /system/build.prop; then
	# emergency boot
	busybox umount /cache
	erase_image cache
	busybox mount -t yaffs2 /dev/block/mtdblock2 /cache
	busybox mkdir /cache/recovery

	image=/stage1/ramdisk-recovery.cpio

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

busybox umount /cache
busybox umount /system

busybox cpio -i < $image

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
echo "stage1 log:" > /dev/kmsg
busybox cat boot.txt > /dev/kmsg
busybox rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init