#!/stage1/busybox sh
export _PATH="$PATH"
export PATH=/stage1

force_recovery="0"

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

busybox mkdir /bada_system
busybox mkdir /bada_user
busybox mkdir /bada_app

busybox chmod 0777 /bada_system
busybox chmod 0777 /bada_user
busybox chmod 0777 /bada_app

# 	aint no readyy
# 	if smth ; then
#		force_recovery="1"
#		busybox mount -t vfat -o noatime /dev/block/platform/s3c-sdhci.0/by-num/p1 /bada_system
#		busybox mount -t vfat -o noatime /dev/block/platform/s3c-sdhci.0/by-num/p2 /bada_user
#		busybox mount -t vfat -o noatime /dev/block/platform/s3c-sdhci.0/by-num/p3 /bada_app
#		mkdir /bada_system/app/
#		mv /bada_app/* /bada_system/app/
#		parted 
#		mkdir /bada_system/app/
#		mkdir /bada_system/user/
# 	fi


busybox mount -t vfat -o noatime /dev/block/mmcblk0p2 /bada_user
busybox mount -t vfat -o noatime /dev/block/mmcblk0p3 /bada_app

if busybox mount | busybox grep -q /bada_user ;
then
	#check partitions existance
	if [ ! -f /bada_user/cache.img ] ; then		
		#18MB cache partition
		make_ext4fs -l 18874368 /bada_user/cache.img
	fi
	if [ ! -f /bada_user/system.img ] ; then			
		#240MB system partition	
		make_ext4fs -l 252143616 /bada_user/system.img		
		force_recovery="1"
	fi
else
	#something went terriwrong
	force_recovery="1"
fi

if busybox mount | busybox grep -q /bada_app ;
then
	if [ ! -f /bada_app/data.img ] ; then		
		#300MB data partition		
		make_ext4fs -l 314572800 /bada_app/data.img
	fi
else
	#something went terriwrong
	force_recovery="1"
fi

busybox echo "force_recovery: $force_recovery"

busybox losetup /dev/loop0 /bada_user/system.img
busybox losetup /dev/loop1 /bada_user/cache.img
busybox mount -t ext4 /dev/loop0 /system
busybox mount -t ext4 /dev/loop1 /cache

image=/stage1/ramdisk.img

if busybox test -e /cache/.startrecovery || busybox grep -q bootmode=2 /proc/cmdline || [ "$force_recovery" -eq "1" ] ; then
	# recovery boot
	busybox rm -fr /cache/.startrecovery
	image=/stage1/ramdisk-recovery.img

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
elif ! busybox test -e /system/build.prop; then
	# emergency boot
	busybox umount /cache

	erase_image /dev/loop1

	busybox mount -t ext4 /dev/loop1 /cache


#	busybox mount -t vfat /dev/block/mmcblk0p2 /sdcard	

	UPDATE=$(busybox cat /bada_user/cyanogenmod.cfg)

	if busybox test -e $UPDATE ; then
		busybox mkdir /cache/recovery
		busybox echo "install_zip(\"`echo $UPDATE`\");" > /cache/recovery/extendedcommand
	fi

	image=/stage1/ramdisk-recovery.img

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

busybox umount /cache
busybox umount /system
busybox losetup -d /dev/loop2
busybox losetup -d /dev/loop1
busybox losetup -d /dev/loop0
busybox umount /bada_system
busybox umount /bada_user
busybox umount /bada_app
busybox rmdir /bada_system
busybox rmdir /bada_user
busybox rmdir /bada_app


busybox zcat $image | busybox cpio -i

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
busybox rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init
